apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: gio-ingress-voting-app
  namespace: gio
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
  - host: gio.vote.diogohack.shop
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: gio-svc-vote
            port:
              number: 80

  - host: gio.result.diogohack.shop
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: gio-svc-result
            port:
              number: 80
