apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: gio-ingress-voting-app
  namespace: gio
  annotations:

spec:
  ingressClassName: "nginx"
  rules:
  - http:
      paths:
      - path: /gio/vote
        pathType: Prefix
        backend:
          service:
            name: gio-svc-vote
            port:
              number: 80
      - path: /result
        pathType: Prefix
        backend:
          service:
            name: gio-svc-result
            port:
              number: 5001
