apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: gio-voting-app-ingress
  namespace: gio
  annotations:

spec:
  ingressClassName: "nginx"
  rules:
  - http:
      paths:
      - path: /vote
        pathType: Prefix
        backend:
          service:
            name: gio-vote-svc
            port:
              number: 80
      - path: /result
        pathType: Prefix
        backend:
          service:
            name: gio-result-svc
            port:
              number: 5001
