apiVersion: apps/v1
kind: Deployment
metadata:
  name: gio-deployment-postgres
  namespace: gio
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gio-postgres
  template:
    metadata:
      labels:
        app: gio-postgres
    spec:

      # --- Init container para preparar el directorio de datos ---
      initContainers:
      - name: init-postgres-data
        image: busybox:1.36
        command:
          - sh
          - -c
          - |
            mkdir -p /var/lib/postgresql/data/pgdata
            chown -R 999:999 /var/lib/postgresql/data
        volumeMounts:
        - name: gio-postgres-storage
          mountPath: /var/lib/postgresql/data

      containers:
      - name: gio-postgres
        image: postgres:15
        ports:
        - containerPort: 5432

        env:
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: db-credentials
              key: POSTGRES_USER

        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-credentials
              key: POSTGRES_PASSWORD

        - name: POSTGRES_DB
          valueFrom:
            secretKeyRef:
              name: db-credentials
              key: POSTGRES_DB

        # *** PGDATA corregido ***
        - name: PGDATA
          value: /var/lib/postgresql/data/pgdata

        volumeMounts:
        - mountPath: /var/lib/postgresql/data
          name: gio-postgres-storage

      volumes:
      - name: gio-postgres-storage
        persistentVolumeClaim:
          claimName: gio-pvc-postgres

---

apiVersion: v1
kind: Service
metadata:
  name: gio-svc-postgres
  namespace: gio
spec:
  selector:
    app: gio-postgres
  ports:
    - port: 5432
      targetPort: 5432
  type: ClusterIP
