name: CI/CD Pipeline

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:

    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    # ---------------------- BUILD + PUSH VOTE ----------------------
    - name: Build and push vote
      run: |
        docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/vote:latest ./vote
        docker push ${{ secrets.DOCKERHUB_USERNAME }}/vote:latest

    # ---------------------- BUILD + PUSH RESULT ----------------------
    - name: Build and push result
      run: |
        docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/result:latest ./result
        docker push ${{ secrets.DOCKERHUB_USERNAME }}/result:latest

    # ---------------------- BUILD + PUSH WORKER ----------------------
    - name: Build and push worker
      run: |
        docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/worker:latest ./worker
        docker push ${{ secrets.DOCKERHUB_USERNAME }}/worker:latest
