apiVersion: apps/v1
kind: Deployment
metadata:
  name: gio-deployment-result
  namespace: gio
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gio-result
  template:
    metadata:
      labels:
        app: gio-result
    spec:
      containers:
      - name: gio-result
        image: josueegm/result:latest
        ports:
        - containerPort: 5001

        env:
        # ---- Postgres connection ----
        - name: PG_HOST
          value: gio-svc-postgres

        - name: PG_PORT
          value: "5432"

        - name: PG_USER
          valueFrom:
            secretKeyRef:
              name: db-credentials
              key: POSTGRES_USER

        - name: PG_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-credentials
              key: POSTGRES_PASSWORD

        - name: PG_DATABASE
          valueFrom:
            secretKeyRef:
              name: db-credentials
              key: POSTGRES_DB

        readinessProbe:
          httpGet:
            path: /
            port: 5001
          initialDelaySeconds: 5
          periodSeconds: 10

        livenessProbe:
          httpGet:
            path: /
            port: 5001
          initialDelaySeconds: 15
          periodSeconds: 20
---
apiVersion: v1
kind: Service
metadata:
  name: gio-svc-result
  namespace: gio
spec:
  selector:
    app: gio-result
  ports:
    - port: 5001
      targetPort: 5001
  type: ClusterIP
