apiVersion: apps/v1
kind: Deployment
metadata:
  name: gio-deployment-vote
  namespace: gio
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gio-vote
  template:
    metadata:
      labels:
        app: gio-vote
    spec:
      containers:
      - name: gio-vote
        image: josueegm/vote:latest
        ports:
        - containerPort: 80
        env:
        - name: REDIS_HOST
          value: gio-svc-redis
        - name: REDIS_PORT
          value: "6379"
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 15
          periodSeconds: 20
---
apiVersion: v1
kind: Service
metadata:
  name: gio-svc-vote
  namespace: gio
spec:
  selector:
    app: gio-vote
  ports:
    - port: 80
      targetPort: 80
  type: ClusterIP
