apiVersion: apps/v1
kind: Deployment
metadata:
  name: gio-deployment-worker
  namespace: gio
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gio-worker
  template:
    metadata:
      labels:
        app: gio-worker
    spec:
      containers:
      - name: gio-worker
        image: josueegm/worker:latest
        ports:
        - containerPort: 80

        env:
        # ---- Redis connection ----
        - name: REDIS_HOST
          value: gio-svc-redis

        # ---- Postgres connection ----
        - name: DB_HOST
          value: gio-svc-postgres

        - name: DB_USERNAME
          valueFrom:
            secretKeyRef:
              name: db-credentials
              key: POSTGRES_USER

        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-credentials
              key: POSTGRES_PASSWORD

        - name: DB_NAME
          valueFrom:
            secretKeyRef:
              name: db-credentials
              key: POSTGRES_DB
---
apiVersion: v1
kind: Service
metadata:
  name: gio-svc-worker
  namespace: gio
spec:
  selector:
    app: gio-worker
  ports:
    - port: 80
      targetPort: 80
  type: ClusterIP
